[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "node ultra-simple-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10