services:
  - type: web
    name: hairfy-whatsapp
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: node production-server.js
    healthCheckPath: /api/health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    disk:
      name: whatsapp-sessions
      mountPath: /opt/render/project/src/.wwebjs_auth
      sizeGB: 1