name: hairfy-whatsapp
services:
- name: web
  source_dir: /
  github:
    repo: your-username/your-repo
    branch: main
  run_command: node production-server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /api/health
  envs:
  - key: NODE_ENV
    value: production
  - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
    value: "true"
  - key: PUPPETEER_EXECUTABLE_PATH
    value: /usr/bin/google-chrome-stable