name: hairfy-external-evolution
services:
- name: web
  source_dir: /
  github:
    repo: olucasvolk/hairfy
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3001
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3001"
  - key: EVOLUTION_API_URL
    value: "https://sua-evolution-api.com"
  - key: EVOLUTION_API_KEY
    value: "sua-chave-aqui"