name: hairfy-whatsapp
services:
- name: web
  source_dir: /
  github:
    repo: seu-usuario/seu-repo
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3001
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3001"
  - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
    value: "false"
  - key: PUPPETEER_EXECUTABLE_PATH
    value: ""