name: hairfy-uaz-whatsapp
services:
- name: web
  source_dir: /
  github:
    repo: olucasvolk/hairfy
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3001
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3001"